### PR TITLE
Added Test for Arrays API

### PR DESCRIPTION
**Pull request by r-sreesaran**
Added Test for Arrays API. Kindly review them and merge. 

--R.Sreesaran

### CODE REVIEW

**Comment by narendranss** [comment]
@r-sreesaran 
Does these test cases do test java 9 changes in arrays?

**Comment by r-sreesaran** [comment]
They dont cover 9, they cover 8. I am adding test cases for all methods.
shall i change it to cover 1.9 alone ?

**Comment by narendranss** [comment]
Yes, in this project only new JDK 9 features need to be added.

Please check the kanban for contributing towards missing jdk9 features.
https://github.com/orgs/Wildcraft/projects/1

If you like to add features for jdk 5, 7 or 8. I have created separate projects for the same. You can add them to their respective projects.

**Comment by narendranss** [comment]
@r-sreesaran - Two things to take care.
1. jdk must be oraclejdk9, check this link, 
https://github.com/travis-ci/travis-ci/issues/5520
2. The changes has conflict. you need to sync with master and submit the pull request

**Comment by r-sreesaran** [comment]
The conflicts have been resolved and working on including oracle jdk 9

**Pull request merged**
